### ISSUE TITLE
Shiny server license / Shiny Server demos

### ISSUE THREAD

**Issue by philibe** [daattali/daattali.github.io#26]
Hello.

Your Shiny Server demos don't work anymore. :)

Screenshot:

![16785621412440](https://user-images.githubusercontent.com/10106259/224507520-5f76ff8b-2e57-4219-a2e7-0d4820b1af4e.jpg)

**Comment by daattali** [comment]
Thanks. I'll have to repurchase a license this week. This will resolve next week.

**Comment by daattali** [comment]
It's back up
